// import './03_promise.resolve'
// import './04_promise.reject'
// import './05_promise.all'
// import './06_promise.race'
// import './07_promise.then返回值'
// import './08_异常穿透'
import './09_中断promise链'
